[options]
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    enable_guicolors = false
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = false
    enable_statusline_mode = true
    relativenumber = false
    enable_vimfiler_filetypeicon = false
    disabled_plugins = ["neomake"]

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = "colorscheme"

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'git'

